In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

In [3]:
df=pd.read_csv('online_retail.csv')
df

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...,...
541904,541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [4]:
from sklearn.ensemble import IsolationForest
tranzaksiyalar=np.array([
    [45000],[50000],[48000],[51000],
    [49000],[470000],[500000000]
])
model=IsolationForest(contamination=0.15, random_state=42)
natija=model.fit_predict(tranzaksiyalar)
print("utkizma holati", natija)

utkizma holati [ 1  1  1  1  1  1 -1]

In [6]:
df.isnull().sum()

index               0
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   index        541909 non-null  int64
 1   InvoiceNo    541909 non-null  object
 2   StockCode    541909 non-null  object
 3   Description  540455 non-null  object
 4   Quantity     541909 non-null  int64
 5   InvoiceDate  541909 non-null  object
 6   UnitPrice    541909 non-null  float64
 7   CustomerID   406829 non-null  float64
 8   Country      541909 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 37.2+ MB

In [8]:
df.describe()

               index       Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  541909.000000  406829.000000
mean   270954.000000       9.552250       4.611114   15287.690570
std    156435.797851     218.081158      96.759853    1713.600303
min         0.000000  -80995.000000  -11062.060000   12346.000000
25%    135477.000000       1.000000       1.250000   13953.000000
50%    270954.000000       3.000000       2.080000   15152.000000
75%    406431.000000      10.000000       4.130000   16791.000000
max    541908.000000   80995.000000   38970.000000   18287.000000

In [9]:
print("Dublikatlar soni:", df.duplicated().sum())

Dublikatlar soni: 0

In [10]:
df = df.drop(columns=['CustomerID'])

In [11]:
df['Description'] = df['Description'].fillna('nomsiz_mahsulot')

In [12]:

print(df.isnull().sum())

index          0
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
Country        0
dtype: int64

In [13]:
df['InvoiceNo'].astype(str).str.startswith('C').value_counts()

InvoiceNo
False    532621
True       9288
Name: count, dtype: int64

In [14]:
df = df[
    ~df['InvoiceNo'].astype(str).str.startswith('C')
]

In [15]:
df['InvoiceNo'].astype(str).str.startswith('C').value_counts()

InvoiceNo
False    532621
Name: count, dtype: int64

In [16]:
df['Quantity'].describe()

count    532621.000000
mean         10.239972
std         159.593551
min       -9600.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       80995.000000
Name: Quantity, dtype: float64

In [17]:
df = df[df['Quantity'] > 0]

In [18]:
print("Quantity <= 0:", (df['Quantity'] <= 0).sum())

Quantity <= 0: 0

In [19]:
df['UnitPrice'].describe()

count    531285.000000
mean          3.857296
std          41.810047
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       13541.330000
Name: UnitPrice, dtype: float64

In [20]:
print("UnitPrice <= 0:", (df['UnitPrice'] <= 0).sum())

UnitPrice <= 0: 1181

In [22]:
df = df[df['UnitPrice'] > 0]

In [23]:
print("UnitPrice <= 0:", (df['UnitPrice'] <= 0).sum())

UnitPrice <= 0: 0